course:
    name: BIZLEGFOSS
    desc: The RIT Business &amp; Legal Aspects of Free/Open Source Software Course
    place: RIT
    start: 2015-01-26
    end: 2015-05-13
    times: Tues & Thurs 2:00PM - 3:15PM
    course: 4085.583.01
    location: Orange Hall (ORN)-1380
    final: "Tues 05/19/15 - 12:30-2:30, (ORN)-1380"
    repo: "http://github.com/decause/bizlegfoss"

instructor:
    name: Remy DeCausemaker
    email: remydcsi@rit.edu
    irc: decause
    avatar: http://www.libravatar.org/user/5d9d0a14af042b2f7877ab58de9b7702ca29bb9d34155dc58eff4ff6509d562c.png
    openhub: decause
    coderwall: decause
    twitter: Remy_D
    office:
        location: RIT MAGIC Center - SIH 1680
        hours: Tuesday, Thursday, 1:00-2:00pm
    links:
        blog: http://opensource.com/users/remyd
        linkedin: http://linkedin.com/in/decause
        github: http://github.com/decause

assistant:
    name: teebeedee
    email: teebeedee@rit.edu
    irc: teebeedee

